### ISSUE TITLE
Random Error: No New Platform Spawns After Landing on Highest Platform

### ISSUE THREAD

**Issue by Bernard-ctrl** [yijiechoo16163/PSC-python-hackathon-2024#7]
### Description
Occasionally, when the player lands on the highest platform, no new platform spawns. While it appears random, I suspect there may be an underlying issue causing this behavior, but I haven't been able to pinpoint the exact reason.

### Steps to Reproduce:

1. Start the game.
2. Progress until the player lands on the highest platform.
3. Observe whether a new platform spawns.

### Expected Behavior
A new platform should spawn every time the player lands on the highest platform, ensuring continuous gameplay.

Actual Behavior: In some instances, no new platform spawns after the player lands on the highest platform, causing the game to stall.

### Environment

Operating System: Windows 11
Game Version: v1.0

### Possible Solution
Although I haven’t identified the root cause, it may be related to how platforms are spawned when the player reaches the highest point. Perhaps there’s a condition or event that fails to trigger under certain circumstances.

### Additional Information
The issue doesn’t occur consistently, but it happens often enough to disrupt gameplay.
Include any other details that might help in debugging the issue, such as patterns noticed when the bug occurs.

**Comment by Bernard-ctrl** [comment]
Suggestion: Add duration between every jumps.

**Comment by yijiechoo16163** [comment]
Add alternative option to spawn new platform:
If bug exist, jump again to spawn.
